dependencies:
 - python=3.6
 - pip:
  - spacy
  - ipykernel
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - sklearn
  - pandas
  - tqdm
  - xgboost
  - Pillow
  - sympy
  - requests
  - lightgbm
  - catboost
  - thinc
